### ISSUE TITLE
Pipeline Umwandlung der Daten in Lindas schreiben

### ISSUE THREAD

**Issue by l00mi** [zazuko/ld-widget#2]
- [x] Graph beantragen: https://lindas.admin.ch/fsvo/rabies-titer-check
- [x] Pipeline bauen: vermutlich Schema.org, oder cube.link (Tägliche Aktualisierung)
- [ ] Deployment: TEST, INT, PROD

**Comment by Irosch** [comment]
@ktk Ludovic did his task https://github.com/zazuko/ld-widget/issues/5. Subdomain is created and deployment should be possible. What do you think? Can this issue be done till 31.3?

**Comment by ktk** [comment]
Deployment:

- [x] TEST (manual)
- [x] INT(in pipeline)
- [ ] PROD

**Comment by BenjaminHofstetter** [comment]
@ktk I think we can close this?
