### ISSUE TITLE
Create Docker Image and deploy on subdomain

### ISSUE THREAD

**Issue by Irosch** [zazuko/ld-widget#5]

**Comment by Irosch** [comment]
Proposal: widget.ld.admin.ch

Wrote an E-mail to Pierre to create the new subdomain.

**Comment by Irosch** [comment]
@ludovicm67 
Question from Pierre: Est-ce que ce subdomain doit pointer sur la même cible que les autres : [cname.cluster.ldbar.ch](http://cname.cluster.ldbar.ch/)

**Comment by ludovicm67** [comment]
@Irosch yes, since the idea is to deploy it there, having a CNAME pointing to this record will be great!

**Comment by ludovicm67** [comment]
#### For the Docker image

I did the changes so that it is able to build and push the Docker image in this PR: #6.
Waiting for a review, or I can directly merge.

#### Domain name

I checked this morning the record, and it was not working.
Re-checking just now, it seems that it is now configured.
So it was done during the morning.
So this point is also OK.

#### Deployment

I'm preparing the required steps for deploying the app on the same cluster as LINDAS.

**Comment by Irosch** [comment]
@ludovicm67 yes exactly, this is what Pierre wrote:

Le sous-domaine [widget.ld.admin.ch](http://widget.ld.admin.ch/) a été créé.
Il y a peut-être encore quelque chose à faire du côté de VSHN.
 
Si c’est le cas, merci de me dire ce que je dois commander chez VSHN pour que ça fonctionne.
Comme ça je peux commander en même temps le sous-domaine et la configuration chez VSHN.

**Comment by ludovicm67** [comment]
I prepared a [merge request](https://gitlab.ldbar.ch/vshn/gitops-main/-/merge_requests/167) with all required resources. Needs to be reviewed and merged by VSHN before being deployed.

**Comment by ludovicm67** [comment]
@Irosch **Update:** it was deployed.
Every commit pushed on the `main` branch will trigger a new deployment.
So from my side, the work is done here.

**Comment by Irosch** [comment]
@ludovicm67 do we need anything from VSHN?

**Comment by ludovicm67** [comment]
@Irosch I don't think so. Everything is up and running.

**Comment by Irosch** [comment]
Hi @ludovicm67 
I got an e-mail from Pierre:

Désolé, je dois faire un changement dans ta commande de CName.
Les subdomains de [ld.admin.ch](http://ld.admin.ch/) sont réservés aux thèmes des datasets et ne devraient pas inclure des applications ou autre chose.
 
J’ai donc commandé à la place [widget.lindas.admin.ch](http://widget.lindas.admin.ch/)
Je supprimerai [widget.ld.admin.ch](http://widget.ld.admin.ch/) quand le nouveau subdomain sera opérationnel
C’est bon pour vous ?

What do you think?

**Comment by Irosch** [comment]
@ludovicm67 latest e-mail from Pierre:
widget.lindas.admin.ch est prêt.
Je te laisse tester. Si c’est en ordre, je vais effacer widget.ld.admin.ch.

**Comment by ludovicm67** [comment]
Merge request for this change created here: https://gitlab.ldbar.ch/vshn/gitops-main/-/merge_requests/171
Waiting for the merge by VSHN.

**Comment by ludovicm67** [comment]
@Irosch The merge request was merged.
You can tell Pierre that `widget.lindas.admin.ch` is working and that he can remove `widget.ld.admin.ch`.
From my side, everything is OK regarding this topic.

**Comment by ludovicm67** [comment]
@Irosch can this issue be closed?
